name: Upload PyCharm installers to Google Drive

on:
  schedule:
    - cron: '0 10 */14 * *'  # каждые 14 дней в 10:00 UTC
  workflow_dispatch:         # ручной запуск

jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Run script
        env:
          GDRIVE_CREDENTIALS: ${{ secrets.GDRIVE_CREDENTIALS }}
        run: node index.js
